### ISSUE TITLE
Strange behavior with Apache Benchmark 

### ISSUE THREAD

**Issue by vuliad** [amphp/aerys#88] opened 2016-04-18 01:22 UTC
Hello! 
While benchmarking basic "helloworld" application found out some really strange behavior.

```php
$router = \Aerys\router()
    ->get("/res_end", function (Request $req, Response $res) {
        $res->end("<html><body><h1>Hello, world.</h1></body></html>");
    })
    ->get("/res_stream", function (Request $req, Response $res) {
        $res->stream("<html><body><h1>Hello, world.</h1></body></html>");
    });
```

While simply running 
> ab -n 10 -c 2 http://192.168.56.102:1337/res_end

it stucks and give this results:
```
Requests per second:    0.29 [#/sec] (mean)
Time per request:       6950.447 [ms] (mean)
Time per request:       3475.223 [ms] (mean, across all concurrent requests)

```

While running 
> ab -n 10 -c 2 http://192.168.56.102:1337/res_stream

everything is ok:
```
Requests per second:    1802.78 [#/sec] (mean)
Time per request:       1.109 [ms] (mean)
Time per request:       0.555 [ms] (mean, across all concurrent requests)
```

At the same time if we force ab use KeepAlive
> ab -k -n 10000 -c 20 http://192.168.56.102:1337/res_end

it stop stucking and give me this results:
```
Requests per second:    5763.61 [#/sec] (mean)
Time per request:       3.470 [ms] (mean)
Time per request:       0.174 [ms] (mean, across all concurrent requests)
```

Full report
```bash
root@ubuntu:/home/vuliad# ab -n 10 -c 2 http://192.168.56.102:1337/res_end
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 192.168.56.102 (be patient).....done


Server Software:
Server Hostname:        192.168.56.102
Server Port:            1337

Document Path:          /res_end
Document Length:        48 bytes

Concurrency Level:      2
Time taken for tests:   33.356 seconds
Complete requests:      10
Failed requests:        0
Total transferred:      1940 bytes
HTML transferred:       480 bytes
Requests per second:    0.30 [#/sec] (mean)
Time per request:       6671.245 [ms] (mean)
Time per request:       3335.622 [ms] (mean, across all concurrent requests)
Transfer rate:          0.06 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       1
Processing:  6014 6671 446.8   7004    7011
Waiting:        0    1   0.2      1       1
Total:       6014 6671 446.7   7005    7011

Percentage of the requests served within a certain time (ms)
  50%   7005
  66%   7009
  75%   7009
  80%   7011
  90%   7011
  95%   7011
  98%   7011
  99%   7011
 100%   7011 (longest request)
```
Target server
```
root@ubuntu2:/tmp/php-uv# php -v
PHP 7.0.5-3+donate.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

php-uv = https://github.com/bwoebi/php-uv@master
libuv = v1.6.1
```

**Comment by kelunik** [comment] 2016-04-18 06:25
Does that also happen without UV?

**Comment by vuliad** [comment] 2016-04-18 09:51
Yes, its the same. 
There is more one thing: I can refresh page in browser and it load without stucking at the same time as ab doing its slow benchmark. So i think for some reason - ab do not understand - that this is the end of request and just waiting for something.

**Comment by bwoebi** [comment] 2016-04-18 10:05
I've observed that behavior with ab too, hence I'm using wrk (https://github.com/wg/wrk) currently, which works … I should debug it …

**Comment by bwoebi** [comment] 2016-04-18 22:04
Fixed (no tag yet); the issue is that ab is using HTTP/1.0 to benchmark and is waiting for the connections to be closed … and as I wasn't closing them... ;-)

**Closed** 2016-04-18 22:05 UTC

**Comment by staabm** [comment] 2016-04-18 22:12
Fix was https://github.com/amphp/aerys/commit/2676b2a7bb9d4bcacf82a633b754a5f18e40e26a
