### ISSUE TITLE
Upgrade deflateResponseFilter() to support non-text/* MIME types

### ISSUE THREAD

**Issue by joshdifabio** [amphp/aerys#112] opened 2016-12-15 14:44 UTC
It'd be great to be able to deflate _application/x-javascript_, _application/json_, etc. Javascript files in particular are often very weighty, even when minified.

Currently [there's a todo for this within `deflateResponseFilter()`](https://github.com/amphp/aerys/blob/9cae6c9fd93136b1db33f770e0a981573b63c220/lib/functions.php#L424); I'm just expressing interest in seeing it implemented.

**Comment by kelunik** [comment] 2016-12-15 15:35
Question is which ones should be compressed.

**Comment by joshdifabio** [comment] 2016-12-15 16:00
> Question is which ones should be compressed.

The todo in the code seems to propose a new configuration option to allow the end user to define that, which would be consistent with nginx and Apache.

**Comment by bwoebi** [comment] 2016-12-15 18:52
How to best implement that? An option which accepts a list with allowed prefixes?

**Comment by kelunik** [comment] 2016-12-15 19:40
Content types I guess, not prefixes

**Comment by bwoebi** [comment] 2016-12-15 19:49
@kelunik I mean by prefix of the content type. I.e. If you want to straight ahead deflate everything with a text/* mime, you just pass in "text/" instead of tens of combinations.

**Comment by kelunik** [comment] 2016-12-15 19:52
Yes, and I think we should not do that. We should compress `text/*` by default and then additional content types present in the config. I don't think prefixes make sense aside from `text/`.

**Comment by staabm** [comment] 2016-12-15 23:06
You will want to compress text based format, like css/js/svg but not files etc... I guess some sane default can match 90% of the use-cases

**Comment by kelunik** [comment] 2016-12-16 08:23
@staabm The issue is that JS is usually served as `application/x-javascript` instead of `text/javascript`.

I think we should always compress `text/*` and default the option to `application/x-javascript` and `application/json`.

**Comment by staabm** [comment] 2016-12-16 09:19
with text-based I did not technically meant text/* but "everything which is regular text content".

I guess something like
- text/*
- */xml
- /*+xml
- /*javascript

could do as a default

**Comment by bwoebi** [comment] 2016-12-16 10:59
Thus I think a simple regex should express that easily?

(i.e. `#^(?:text/.*+|[^/]*+/xml|[^+]*\+xml|application/(?:json|(?:x-)?javascript))$#`)

Then you can customize as much as you want to…

**Comment by joshdifabio** [comment] 2016-12-16 12:00
I think regex support would be good.

**Comment by kelunik** [comment] 2016-12-16 12:34
As long as the regex is fast enough, it's fine. It's a rather hot one that's hit on every single request. The chance of people shooting into their own foot is rather high compared to a simple list which can be done with a simple array index lookup in O(1). The number of content types one serves is usually pretty limited.

**Comment by bwoebi** [comment] 2016-12-16 13:03
Good, I'll prepare a patch supporting regex and usually matching in O(1)

(I will create a fast-lookup map by matching against the known mime-types (from the mimefile) ahead of time, and falling back to regex if that mimetype isn't known.)

That should be the most flexible solution while still providing enough speed.

**Comment by kelunik** [comment] 2016-12-16 13:37
@bwoebi You don't need to check mime-types from the mimefile ahead of time. Just cache the content types in a look-up array.

**Comment by rdlowrey** [comment] 2016-12-16 21:55
I originally avoided regex here because perf. Ideally people specify the specific content types they wish to deflate so you can do a simple hash table lookup.

Beyond that you can use string functions to check the prefix for things like `text/` matches. If we add the option for regex we should likely keep an in-memory LRU cache in a hash map for fast `isset` lookups before resorting to regex on every request.

Alternatively, it would be nice to have the regex checks be an option that you can turn on or off for perf reasons.

**Comment by bwoebi** [comment] 2016-12-16 22:01
@rdlowrey No need to worry about perf, as @kelunik we may just cache the already checked content types and thus just have the overhead once per content-type for the whole lifetime of the server.

**Comment by rdlowrey** [comment] 2016-12-16 22:08
Sure, just make sure the number of cached entries have a limit otherwise it's a memory leak

**Comment by bwoebi** [comment] 2016-12-22 19:57
Fixed by 544ee5f152db53f8a0fc79644131d13ac68d36a3

**Closed by bwoebi** 2016-12-22 19:57 UTC
Labels: feature request
