### ISSUE TITLE
Output to STDOUT crashes workers

### ISSUE THREAD

**Issue by kelunik** [amphp/aerys#57] opened 2015-11-04 23:35 UTC
This issue may also have affected @assertchris during the stream on Twitch. Output is not forwarded to the master process, because it's not supported on Windows. Maybe we can emit warnings or use a output buffer and send it via sockets on Windows?

**Comment by bwoebi** [comment] 2015-11-05 00:02
Fixed via 82efb61

**Closed by bwoebi** 2015-11-05 00:02 UTC
Labels: bug

**Comment by assertchris** [comment] 2015-11-05 00:04
:+1:

**Comment by lt** [comment] 2015-11-05 08:09
This is the issue I was talking to Bob about a couple of weeks back when I was copying the aerys master / worker code to another project. Sorry didnt think to file a bug report, as I thought it was by design that nothing was sent to stdout and I had broken that design.

Same probably happens with stderr?

On the back of this I encountered another issue. If you leave the pipes from `proc_open` open, but do not actually read from them, and there is output in the buffer when the process ends then `proc_get_status` will still show the process as running until outputs have been drained. Something to bare in mind if you ever leave the pipes open, attach read handlers.

**Comment by bwoebi** [comment] 2015-11-05 13:46
Well, if you write directly to php://stdout or php://stderr, there's nothing I can do about it.
All I can do is trying to prevent it from crashing then, hence I've put a pcntl_signal(SIGPIPE, SIG_IGN);` into aerys-worker.
