### ISSUE TITLE
js or css files on HTTP/2

### ISSUE THREAD

**Issue by laurenti** [amphp/aerys#107] opened 2016-10-26 17:41 UTC
I have problem with load js or css file.
simple test.php

> <?php
> use Aerys{ Host, Request, Response, function root, function router };
> $router = router()
>     ->get("/", function(Request $req, Response $res){
>           $res->end("
>                      on head -> script with src='/js/jquery-1.12.4.min.js' type='text/javascript'
>                      on body -> Hello, world
>               ");  
>     });
> $root = root("/path/to/public",["mimeFile"=>"/path/to/mime"]);
> (new Host)
>     ->name("site_name")
>     ->expose("*", 443)
>     ->encrypt("/path/to/certificate.pem", "/path/to/private.pem")
>     ->use($router)
>     ->use($root);

attached test.php : 
[test.txt](https://github.com/amphp/aerys/files/554048/test.txt)

run command : `php bin/aerys -d -c test.php`
remains stuck on loading js file
I should make any specific settings?

**Comment by bwoebi** [comment] 2016-10-26 20:13
This shouldn't be stuck nor require extra settings. Perhaps there's a bug with large js files (like your jquery one…)

I at least locally cannot reproduce any failure. I have no idea what it could be related to either.

I'd welcome you to debug yourself a bit; or alternatively, may I look around on your end? (ssh or supervised via teamviewer, doesn't matter)

**Comment by laurenti** [comment] 2016-10-27 13:23
If you don't mind, I can send to your mail id and pass for TeamViewer.
Just tell me when you have time. Thank you.

**Comment by bwoebi** [comment] 2016-10-27 13:31
@laurenti I do have time right now ;-)

**Comment by laurenti** [comment] 2016-10-27 13:34
yes

**Comment by laurenti** [comment] 2016-10-27 13:34
send to mail

**Comment by bwoebi** [comment] 2016-10-27 15:16
Thanks…

It's a general TLS issue, unrelated to HTTP/1 or 2.

I still have no idea what the openssl issue is.

Perhaps someone knows how `SSL routines:SSL3_WRITE_PENDING: bad write retry` ought to be fixed. \cc @bukka @rdlowrey (?)

**Comment by laurenti** [comment] 2016-10-27 15:20
ok. Thank you for your efforts

**Comment by Fedott** [comment] 2016-11-10 01:27
Hi.
This problem is a bug in php (or OpenSSL)
There is a ticket https://bugs.php.net/bug.php?id=72333

**Comment by bwoebi** [comment] 2016-11-10 10:18
@Fedott thank you for investigating more.

@bukka Can you please have a look at that bug report? Thanks a lot!

**Comment by bukka** [comment] 2016-11-13 15:09
@bwoebi I'm a bit busy with some other stuff but should have more time in December so will take a look on this one then ;)

**Comment by bwoebi** [comment] 2016-12-16 20:34
@bukka ping, again … it's December, do you have the time to look after it?

**Comment by bukka** [comment] 2017-01-02 20:36
I finally took a look and put together some local tests. I have assigned it to myself but will need to think about it a bit more.

**Comment by kelunik** [comment] 2017-03-05 14:42
@bwoebi Looks like the patch still doesn't land in the next version, can we work around this issue by specifying a fixed lower `$length` for [`fwrite`](https://github.com/amphp/aerys/blob/113f1cc417e85fe872d726e9a9c38785dad86a01/lib/Server.php#L437)?

**Comment by kelunik** [comment] 2017-03-14 19:05
Closing as https://github.com/php/php-src/pull/2330 has been merged.

**Closed by kelunik** 2017-03-14 19:05 UTC
Labels: blocked, bug
