### ISSUE TITLE
Crashes on certain requests

### ISSUE THREAD

**Issue by PeeHaa** [amphp/aerys#132] opened 2017-02-21 11:21 UTC
We are getting crashes on some requests:

> GitAmp-Ubuntu php[12165]: [2017-02-10 10:06:37] critical LogicException: Cannot update resolved promise in /opt/gitamp/vendor/amphp/amp/lib/PublicPromisor.php:28
GitAmp-Ubuntu php[12165]: Stack trace:
GitAmp-Ubuntu php[12165]: #0 /opt/gitamp/vendor/amphp/aerys/lib/Server.php(591): Amp\Deferred->update('cmd=%63%64%20%2...')
GitAmp-Ubuntu php[12165]: #1 /opt/gitamp/vendor/amphp/aerys/lib/Server.php(567): Aerys\Server->onParsedEntityPart(Object(Aerys\Client), Array)
GitAmp-Ubuntu php[12165]: #2 /opt/gitamp/vendor/amphp/aerys/lib/Http1Driver.php(498): Aerys\Server->onParseEmit(Object(Aerys\Client), 4, Array, NULL)
GitAmp-Ubuntu php[12165]: #3 [internal function]: Aerys\Http1Driver->parser(Object(Aerys\Client))
GitAmp-Ubuntu php[12165]: #4 /opt/gitamp/vendor/amphp/aerys/lib/Server.php(555): Generator->send('POST /command.p...')
GitAmp-Ubuntu php[12165]: #5 /opt/gitamp/vendor/amphp/amp/lib/NativeReactor.php(265): Aerys\Server->onReadable('000000003401e4c...', Resource id #88544, Object(Aerys\Client))
GitAmp-Ubuntu php[12165]: #6 /opt/gitamp/vendor/amphp/amp/lib/NativeReactor.php(249): Amp\NativeReactor->doIoCallback('000000003401e4c...', Object(stdClass), Resource id #88544)
GitAmp-Ubuntu php[12165]: #7 /opt/gitamp/vendor/amphp/amp/lib/NativeReactor.php(214): Amp\NativeReactor->selectActionableStreams(0.8837)
GitAmp-Ubuntu php[12165]: #8 /opt/gitamp/vendor/amphp/amp/lib/NativeReactor.php(71): Amp\NativeReactor->doTick(false)
GitAmp-Ubuntu php[12165]: #9 /opt/gitamp/vendor/amphp/amp/lib/functions.php(46): Amp\NativeReactor->run(Object(Closure))
GitAmp-Ubuntu php[12165]: #10 /opt/gitamp/vendor/amphp/aerys/bin/aerys(99): Amp\run(Object(Closure))
GitAmp-Ubuntu php[12165]: #11 {main}

Not sure yet if random / specific requests yet.

Related to: https://github.com/ekinhbayar/gitamp/issues/35

I added some logging to try to find out what causes this. Will update this issue if I have more information.

**Comment by PeeHaa** [comment] 2017-02-24 11:30
Got another one:

> GitAmp-Ubuntu sshd[19035]: Connection closed by 101.200.160.48 port 35046 [preauth]
GitAmp-Ubuntu php[6184]: [2017-02-24 03:56:44] critical LogicException: Cannot update resolved promise in /opt/gitamp/vendor/amphp/amp/lib/PublicPromisor.php:28
GitAmp-Ubuntu php[6184]: Stack trace:
GitAmp-Ubuntu php[6184]: #0 /opt/gitamp/vendor/amphp/aerys/lib/Server.php(560): Amp\Deferred->update('cmd=%63%64%20%2...')
GitAmp-Ubuntu php[6184]: #1 /opt/gitamp/vendor/amphp/aerys/lib/Server.php(536): Aerys\Server->onParsedEntityPart(Object(Aerys\Client), Array)
GitAmp-Ubuntu php[6184]: #2 /opt/gitamp/vendor/amphp/aerys/lib/Http1Driver.php(498): Aerys\Server->onParseEmit(Object(Aerys\Client), 4, Array, NULL)
GitAmp-Ubuntu php[6184]: #3 [internal function]: Aerys\Http1Driver->parser(Object(Aerys\Client))
GitAmp-Ubuntu php[6184]: #4 /opt/gitamp/vendor/amphp/aerys/lib/Server.php(524): Generator->send('POST /command.p...')
GitAmp-Ubuntu php[6184]: #5 /opt/gitamp/vendor/amphp/amp/lib/UvReactor.php(424): Aerys\Server->onReadable('000000004c939f2...', Resource id #47533, Object(Aerys\Client))
GitAmp-Ubuntu php[6184]: #6 /opt/gitamp/vendor/amphp/amp/lib/UvReactor.php(401): Amp\UvReactor->invokePollWatcher(Object(stdClass))
GitAmp-Ubuntu php[6184]: #7 [internal function]: Amp\UvReactor->Amp\{closure}(Resource id #47534, 0, 1, Resource id #47533)
GitAmp-Ubuntu php[6184]: #8 /opt/gitamp/vendor/amphp/amp/lib/UvReactor.php(93): uv_run(Resource id #56, 1)
GitAmp-Ubuntu php[6184]: #9 /opt/gitamp/vendor/amphp/amp/lib/functions.php(46): Amp\UvReactor->run(Object(Closure))
GitAmp-Ubuntu php[6184]: #10 /opt/gitamp/vendor/amphp/aerys/bin/aerys(106): Amp\run(Object(Closure))
GitAmp-Ubuntu php[6184]: #11 {main}

Sadly our logging doesn't catch these requests.

**Comment by joshdifabio** [comment] 2017-02-24 12:17
I've also seen _Cannot update resolved promise_ a number of times. Unfortunately I don't have time to give more information right now.

**Comment by PeeHaa** [comment] 2017-02-24 12:34
I tried adding logging to find out whether it's specific requests that make crash. But as sad it breaks before reaching [the logger](https://github.com/ekinhbayar/gitamp/blob/master/server.php#L107) or so it seems.

Is there a better way to get more info @kelunik?

**Comment by kelunik** [comment] 2017-02-24 12:36
@PeeHaa Do you still have the Nginx proxy? In that case, could you log all requests to `command.php` or containing `cmd=%63%64` there?

**Comment by PeeHaa** [comment] 2017-02-24 12:39
I think it's directly exposed for gitamp

**Comment by kelunik** [comment] 2017-02-24 17:15
It's failing, because the `bodyPromisor` is already resolved with a `ClientException` here: https://github.com/amphp/aerys/blob/7ddb3770f8fc6f301fe7698de2575af2e49bb80b/lib/Server.php#L903

**Code 2 Reproduce**

```
<?php

require __DIR__ . "/../vendor/autoload.php";

Amp\run(function () use ($argv) {
    $payload = "cmd=%63%64%20%2F%76%61%72%2F%74%6D%70%20%26%26%20%65%63%68%6F%20%2D%6E%65%20%5C%5C%78%33%36%31%30%63%6B%65%72%20%3E%20%36%31%30%63%6B%65%72%2E%74%78%74%20%26%26%20%63%61%74%20%36%31%30%63%6B%65%72%2E%74%78%7";

    $buffer = <<<'HEAD'
POST /command.php HTTP/1.0
Content-Type: application/x-www-form-urlencoded
Host: gitamp.audio
HEAD;

    $buffer = str_replace("\n", "\r\n", trim($buffer)) . "\r\n";
    $buffer .= "Content-Length: " . strlen($payload) . "\r\n";
    $buffer .= "\r\n";
    $buffer .= $payload;

    print "Sending:" . PHP_EOL;
    print $buffer . PHP_EOL;

    $socket = yield Amp\Socket\connect("tcp://localhost:1337");
    Amp\onWritable($socket, function ($watcherId) use ($socket, &$buffer) {
        fwrite($socket, substr($buffer, 0, 8192));
        $buffer = substr($buffer, 8192);

        if (!$buffer) {
            Amp\cancel($watcherId);
        }

        usleep(500000);
    });

    Amp\onReadable($socket, function () use ($socket) {
        $input = fread($socket, 8192);

        if ($input !== false && strlen($input)) {
            print $input;
        } else {
            exit;
        }
    });
});
```

**Comment by kelunik** [comment] 2017-02-24 17:25
This happens if the connection is closed before the body is consumed. For HTTP/1.0 requests / responses that happens once the response body is written. In case the full request-response-cycle is done in a single tick, the connection is closed before the response body is actually streamed.

**Comment by kelunik** [comment] 2017-02-26 11:00
@bwoebi Could you release a new bugfix version, please?

**Comment by bwoebi** [comment] 2017-02-26 12:11
Will do this evening.

**Closed by bwoebi** 2017-02-26 12:11 UTC
Labels: bug
